services:
  db:
    image: postgres:18.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=saas
    ports:
      - "8054:5432"
    volumes:
      - saas_pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - saas_redis_data:/data

volumes:
  saas_pg_data:
    driver: local

  saas_redis_data:
    driver: local
